# Generated by Django 3.0.5 on 2020-04-25 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=320)),
                ('position', models.CharField(max_length=320)),
                ('started_work', models.DateField(default=django.utils.timezone.now)),
                ('left_work', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github_link', models.CharField(blank=True, max_length=240, null=True, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
