# Generated by Django 3.0.5 on 2020-04-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='left_work',
        ),
    ]
